### ISSUE TITLE
I want to build it sooo hard!!! 

### ISSUE THREAD

**Issue by nokomotc** [Pironium/PiroEngine#1]
But I can't. It has no haxe, yoptascript and jsonc files. Fix this please

**Comment by nokomotc** [comment]
R and Scala would be cool too ngl

update: Not necessary, but those seem like some heck good languages for big projects like this

**Comment by nokomotc** [comment]
@n1ses now I wanna sing it

**Comment by tailsjs** [comment]
Hello. We're developing this engine sooo hard yes. Maybe we add this programming lanuages to our engine
